apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ptool
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: ptool-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
