apiVersion: v1
kind: Service
metadata:
  name: ptool
  labels:
    run: ptool
spec:
  type: NodePort
  ports:
   - port: 80
     protocol: TCP
#     nodePort: 32766
  selector:
    run: ptool
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ptool-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: ptool 
    spec:
      containers:
      - name: ptool
        image: smtripat/alpine-apache-k8:v5
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: myregistrykey
