apiVersion: v1
kind: Service
metadata:
  name: my-ptool
  labels:
    run: my-ptool
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-ptool
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-ptool
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-ptool
    spec:
      containers:
      - name: my-ptool
        image: smtripat/alpine-apache-k8:v1
        name: ptool
        volumeMounts:
        - mountPath: /var/www/localhost/htdocs
          name: htdocs
      volumes:
      - name: htdocs
        emptyDir: {}
      imagePullSecrets:
        - name: myregistrykey
       
