apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: staging
spec:
  hard:
    pods: "7"
    requests.cpu: "1000m"
    requests.memory: 1Gi
    limits.cpu: "1600m"
    limits.memory: 2Gi
